market_research:
  description: >
    Research the market for {product_name} targeting {target_audience}. Summarize trends, competitors, and opportunities.
  expected: >
    A concise market snapshot with 3-5 bullet insights.

prepare_marketing_strategy:
  description: >
    Propose a practical strategy and channel mix given a budget of {budget}.
  expected: >
    Strategy brief (channels, budget split, KPIs).

create_content_calendar:
  description: >
    Draft a 2-week social content calendar aligned to the strategy for {product_name}.
  expected: >
    A day-by-day calendar with post ideas and hooks.

prepare_post_drafts:
  description: >
    Create 3 social media post drafts including hashtags for {target_audience}.
  expected: >
    3 drafts in JSON schema.

prepare_scripts_for_reels:
  description: >
    Create 2 short-form video (reels) scripts (≤45s) with hooks and CTAs.
  expected: >
    2 scripts in JSON schema.

content_research_for_blogs:
  description: >
    Research 2 blog topics for {product_name} that resonate with {target_audience}.
  expected: >
    2 outlines with H2/H3s.

draft_blogs:
  description: >
    Write 1 blog draft (~600–800 words) from a chosen outline.
  expected: >
    Blog draft in JSON schema.

seo_optimization:
  description: >
    Provide on-page SEO improvements, target keywords, meta title/description.
  expected: >
    SEO checklist and metadata in JSON schema.
